name: Triggered by Version Bump Release PR

on:
  pull_request:
    paths:
      - '!**'
      - "sovrin/metadata.json"

jobs:
  extract-information:
    name: Extract needed Information for Indy-Test-Automation
    runs-on: ubuntu-latest
    outputs:
      indyVersion: ${{ steps.indy-versions.outputs.indyVersion}}
      sovtokenVersion: ${{ steps.sovtoken-versions.outputs.sovtokenVersion}}
      sovtokenfeesVersion: ${{ steps.sovtoken-versions.outputs.sovtokenfeesVersion}}
      GITHUB_REPOSITORY_NAME: ${{ steps.repository-name.outputs.lowercase }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Convert the GitHub repository name to lowercase
        id: repository-name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Set up python
        run: |
          pip3 install semver
      - name: Get Version with UX-timestamp
        id: version
        run: |
          echo "version=$(python3 updateVersion.py --getVersion)" >> $GITHUB_OUTPUT
      - name: prepare
        run: ./build-scripts/ubuntu-2004/prepare-package.sh ./ ${{ steps.version.outputs.version }}
      - name: Extract Indy Versions
        id: indy-versions
        run:  |
          echo "indyVersion=$(grep -oP "\d+.\d+.\d+((-|.)?rc\d+)?" <<< $(grep -oP "indy-node==\d+.\d+.\d+((-|.)?rc\d+)?" setup.py))" >>$GITHUB_OUTPUT
      - name: Extract sovtoken & sovtokenfees Version
        id: sovtoken-versions
        run: |
          echo "sovtokenVersion=$(grep -oP "\d+.\d+.\d+((-|.)?((rc)|(dev))?\d+)?" <<< $(grep -oP "sovtoken==\d+.\d+.\d+((-|.)?(rc|dev)\d+)?" setup.py))" >>$GITHUB_OUTPUT
          echo "sovtokenfeesVersion=$(grep -oP "\d+.\d+.\d+((-|.)?((rc)|(dev))?\d+)?" <<< $(grep -oP "sovtokenfees==\d+.\d+.\d+((-|.)?(rc|dev)\d+)?" setup.py))" >>$GITHUB_OUTPUT

  build_sovrin:
    name: Build Sovrin Deb
    uses: ./.github/workflows/reuseable_build_package.yaml
    with:
      isDev: false

  call-indy-test-automation:
    name: Indy-Test-Automation
    needs: [extract-information,build_sovrin]
    uses: hyperledger/indy-test-automation/.github/workflows/callable_test-automation-extention.yaml@v0.11
    with:
      ubuntuVersion: "ubuntu-2004"
      libsovtokenJSON: "{\"install\": \"yes\",  \"version\": \"1.0.5\"}"
      libIndyVersion: "1.15.0~1625-bionic"
      includePaymentTests: true
      testAutomationBranch: "v0.11"
      debName: "sovrin_*.deb"
      packageName: "sovrin-deb"

  statusCheck:
    name: statusCheck
    runs-on: ubuntu-latest
    needs: [call-indy-test-automation]
    steps:
      - run: 'echo "Just a status Check (Always true, when executed) for branch protection rules(blocks merging while test are running and if tests fail)." '